import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import {
  FileBarChart,
  Landmark,
  CheckCircle2,
  AlertOctagon,
  FileDown,
  Sparkles,
  ChevronRight,
} from "lucide-react";
import { getAllProjects, getSummaryStats, STATES } from "../data/mockData";
import {
  getStateRiskBarData,
  getStatusDistribution,
  getYearlyFinancials,
  getAnomalyTypeFrequency,
  getTopRiskProjects,
} from "../data/analytics";
import { formatINR, formatFullINR } from "../utils/format";
import { useToast } from "../context/ToastContext";
import StatCard from "../components/common/StatCard";
import { RiskBadge } from "../components/common/Badge";
import Button from "../components/common/Button";
import Modal from "../components/common/Modal";

const RISK_COLORS = { Low: "#22C55E", Medium: "#F5A524", High: "#EF4444" };
const STATUS_COLORS = ["#2454E6", "#22C55E", "#F5A524", "#8B5CF6", "#EF4444"];

const REPORT_TYPES = [
  "State-wise Risk Summary",
  "District-wise Risk Summary",
  "High-Risk Projects Report",
  "Anomaly Trends Report",
];

function buildReportText(type, scope, projects) {
  const stats = getSummaryStats(projects);
  const lines = [
    `MPLADS SENTINEL — ${type.toUpperCase()}`,
    `Scope: ${scope || "All India"}`,
    `Generated on: ${new Date().toLocaleString("en-IN")}`,
    "-".repeat(60),
    `Total Projects: ${stats.total}`,
    `Total Allocation: ${formatFullINR(stats.allocated)}`,
    `Total Expenditure: ${formatFullINR(Math.round(stats.expenditure))}`,
    `Average Risk Score: ${stats.avgRisk}/100`,
    `Low Risk: ${stats.low}  |  Medium Risk: ${stats.medium}  |  High Risk: ${stats.high}`,
    `Anomalies Flagged: ${stats.anomalies}`,
    "-".repeat(60),
    "TOP FLAGGED PROJECTS (requires human review):",
    ...getTopRiskProjects(10)
      .filter((p) => !scope || p.state === scope)
      .slice(0, 10)
      .map((p) => `  • ${p.projectId} — ${p.description} (${p.district}) — Risk ${p.riskScore}/100`),
    "-".repeat(60),
    "NOTE: This report is generated by an AI-assisted monitoring system for",
    "human review. Flags are not proof of fraud or wrongdoing — findings must",
    "be verified by the concerned authority before any action is taken.",
  ];
  return lines.join("\n");
}

function downloadText(filename, text) {
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function GenerateReportForm({ onGenerate }) {
  const [type, setType] = useState(REPORT_TYPES[0]);
  const [scope, setScope] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    onGenerate(type, scope);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <label className="block">
        <span className="mb-1.5 block text-sm font-medium text-ink-700">Report Type *</span>
        <select
          value={type}
          onChange={(e) => setType(e.target.value)}
          className="w-full rounded-lg border border-ink-200 px-3.5 py-2.5 text-sm focus:border-brand-500"
        >
          {REPORT_TYPES.map((t) => (
            <option key={t} value={t}>
              {t}
            </option>
          ))}
        </select>
      </label>
      <label className="block">
        <span className="mb-1.5 block text-sm font-medium text-ink-700">Scope (optional)</span>
        <select
          value={scope}
          onChange={(e) => setScope(e.target.value)}
          className="w-full rounded-lg border border-ink-200 px-3.5 py-2.5 text-sm focus:border-brand-500"
        >
          <option value="">All India</option>
          {STATES.map((s) => (
            <option key={s.code} value={s.name}>
              {s.name}
            </option>
          ))}
        </select>
      </label>
      <Button type="submit" className="w-full" size="lg" icon={Sparkles}>
        Generate Report
      </Button>
    </form>
  );
}

export default function ReportsPage() {
  const navigate = useNavigate();
  const { push } = useToast();
  const [modalOpen, setModalOpen] = useState(false);
  const [recentReports, setRecentReports] = useState([]);

  const projects = useMemo(() => getAllProjects(), []);
  const stats = useMemo(() => getSummaryStats(projects), [projects]);
  const stateRiskData = useMemo(() => getStateRiskBarData(), []);
  const statusData = useMemo(() => getStatusDistribution(), []);
  const yearlyData = useMemo(() => getYearlyFinancials(), []);
  const anomalyTypeData = useMemo(() => getAnomalyTypeFrequency(), []);
  const topRisk = useMemo(() => getTopRiskProjects(6), []);

  const handleGenerate = (type, scope) => {
    const scopedProjects = scope ? projects.filter((p) => p.state === scope) : projects;
    const text = buildReportText(type, scope, scopedProjects);
    const filename = `${type.replace(/\s+/g, "_")}_${scope || "AllIndia"}_${Date.now()}.txt`;
    downloadText(filename, text);

    setRecentReports((prev) => [
      { id: `RPT-${Date.now()}`, type, scope: scope || "All India", generatedOn: new Date().toISOString(), text, filename },
      ...prev,
    ]);
    setModalOpen(false);
    push(`${type} generated and downloaded.`, "success");
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
        <div>
          <h1 className="font-display text-2xl font-bold text-ink-900">Reports &amp; Investigation</h1>
          <p className="mt-1 text-sm text-ink-500">Analytics across the monitored project dataset, and on-demand report generation.</p>
        </div>
        <Button icon={FileBarChart} onClick={() => setModalOpen(true)}>
          Generate Report
        </Button>
      </div>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard icon={Landmark} label="Total Projects" numericValue={stats.total} tone="navy" />
        <StatCard icon={CheckCircle2} label="Completed" numericValue={projects.filter((p) => p.status === "Completed").length} tone="green" />
        <StatCard icon={AlertOctagon} label="Delayed" numericValue={projects.filter((p) => p.status === "Delayed").length} tone="red" />
        <StatCard icon={FileBarChart} label="Total Allocation" value={formatINR(stats.allocated)} tone="purple" />
      </div>

      <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
        <div className="rounded-xl2 border border-ink-200 bg-white p-5 shadow-card">
          <h3 className="mb-1 font-display text-base font-bold text-ink-900">Risk Distribution by State</h3>
          <p className="mb-4 text-xs text-ink-500">Top 10 states by project count</p>
          <ResponsiveContainer width="100%" height={280}>
            <BarChart data={stateRiskData} layout="vertical" margin={{ left: 10 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#EBEFF5" horizontal={false} />
              <XAxis type="number" tick={{ fontSize: 11 }} />
              <YAxis type="category" dataKey="state" width={110} tick={{ fontSize: 11 }} />
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: 11 }} />
              <Bar dataKey="Low" stackId="a" fill={RISK_COLORS.Low} radius={[0, 0, 0, 0]} />
              <Bar dataKey="Medium" stackId="a" fill={RISK_COLORS.Medium} />
              <Bar dataKey="High" stackId="a" fill={RISK_COLORS.High} radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="rounded-xl2 border border-ink-200 bg-white p-5 shadow-card">
          <h3 className="mb-1 font-display text-base font-bold text-ink-900">Project Status Distribution</h3>
          <p className="mb-4 text-xs text-ink-500">Across the full monitored dataset</p>
          <ResponsiveContainer width="100%" height={280}>
            <PieChart>
              <Pie data={statusData} dataKey="count" nameKey="status" innerRadius={60} outerRadius={95} paddingAngle={2}>
                {statusData.map((_, i) => (
                  <Cell key={i} fill={STATUS_COLORS[i % STATUS_COLORS.length]} />
                ))}
              </Pie>
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: 11 }} />
            </PieChart>
          </ResponsiveContainer>
        </div>

        <div className="rounded-xl2 border border-ink-200 bg-white p-5 shadow-card">
          <h3 className="mb-1 font-display text-base font-bold text-ink-900">Allocation vs Expenditure by Year</h3>
          <p className="mb-4 text-xs text-ink-500">₹ in the monitored dataset</p>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={yearlyData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#EBEFF5" />
              <XAxis dataKey="year" tick={{ fontSize: 11 }} />
              <YAxis tickFormatter={(v) => formatINR(v)} tick={{ fontSize: 10 }} width={70} />
              <Tooltip formatter={(v) => formatFullINR(Math.round(v))} />
              <Legend wrapperStyle={{ fontSize: 11 }} />
              <Bar dataKey="allocated" name="Allocated" fill="#AEC6FF" radius={[4, 4, 0, 0]} />
              <Bar dataKey="expenditure" name="Expenditure" fill="#2454E6" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="rounded-xl2 border border-ink-200 bg-white p-5 shadow-card">
          <h3 className="mb-1 font-display text-base font-bold text-ink-900">Anomaly Types Detected</h3>
          <p className="mb-4 text-xs text-ink-500">Frequency across all flagged projects</p>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={anomalyTypeData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#EBEFF5" />
              <XAxis dataKey="type" tick={{ fontSize: 11 }} />
              <YAxis tick={{ fontSize: 11 }} />
              <Tooltip />
              <Bar dataKey="count" fill="#8B5CF6" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="overflow-hidden rounded-xl2 border border-ink-200 bg-white shadow-card">
        <div className="border-b border-ink-100 px-5 py-4">
          <h3 className="font-display text-base font-bold text-ink-900">Top Flagged Projects</h3>
        </div>
        <div className="divide-y divide-ink-50">
          {topRisk.map((p) => (
            <button
              key={p.id}
              onClick={() => navigate(`/project/${encodeURIComponent(p.id)}`)}
              className="flex w-full items-center justify-between gap-3 px-5 py-3.5 text-left transition-colors hover:bg-brand-50/40"
            >
              <div className="min-w-0 flex-1">
                <p className="truncate text-sm font-medium text-ink-900">{p.description}</p>
                <p className="text-xs text-ink-400">
                  {p.projectId} · {p.district}, {p.state}
                </p>
              </div>
              <RiskBadge level={p.riskLevel} size="sm" />
              <ChevronRight size={15} className="shrink-0 text-ink-300" />
            </button>
          ))}
        </div>
      </div>

      <div className="overflow-hidden rounded-xl2 border border-ink-200 bg-white shadow-card">
        <div className="border-b border-ink-100 px-5 py-4">
          <h3 className="font-display text-base font-bold text-ink-900">Recent Reports</h3>
          <p className="mt-0.5 text-xs text-ink-500">Generated in this session</p>
        </div>
        {recentReports.length === 0 ? (
          <div className="px-5 py-10 text-center text-sm text-ink-400">
            No reports generated yet — click "Generate Report" above to create one.
          </div>
        ) : (
          <div className="divide-y divide-ink-50">
            {recentReports.map((r) => (
              <div key={r.id} className="flex items-center justify-between gap-3 px-5 py-3.5">
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium text-ink-900">{r.type}</p>
                  <p className="text-xs text-ink-400">
                    {r.scope} · {new Date(r.generatedOn).toLocaleString("en-IN")}
                  </p>
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  icon={FileDown}
                  onClick={() => downloadText(r.filename, r.text)}
                >
                  Download
                </Button>
              </div>
            ))}
          </div>
        )}
      </div>

      <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Generate Report" subtitle="Creates a downloadable summary from the current dataset.">
        <GenerateReportForm onGenerate={handleGenerate} />
      </Modal>
    </div>
  );
}