import { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { Download, ChevronRight, ShieldAlert, Info, ArrowLeft } from "lucide-react";
import { getProjectById } from "../data/mockData";
import { formatFullINR, formatDate, classNames } from "../utils/format";
import { StatusBadge } from "../components/common/Badge";
import { EmptyState, CardSkeleton } from "../components/common/EmptyState";
import Button from "../components/common/Button";
import RiskGauge from "../components/common/RiskGauge";

const BREAKDOWN_LABELS = {
  financial: "Financial Anomalies",
  delay: "Time Delays",
  resource: "Resource Utilization",
  geo: "Geo-tag Issues",
  document: "Document Mismatch",
};

export default function ScorecardPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [project, setProject] = useState(null);

  useEffect(() => {
    setLoading(true);
    const t = setTimeout(() => {
      setProject(getProjectById(decodeURIComponent(id)));
      setLoading(false);
    }, 450);
    return () => clearTimeout(t);
  }, [id]);

  if (loading) {
    return (
      <div className="space-y-5">
        <div className="grid grid-cols-1 gap-5 lg:grid-cols-3">
          <CardSkeleton />
          <CardSkeleton />
          <CardSkeleton />
        </div>
      </div>
    );
  }

  if (!project) {
    return (
      <EmptyState
        icon={ShieldAlert}
        title="Project not found"
        description="This project id doesn't exist in the current dataset."
        action={
          <Button variant="outline" onClick={() => navigate("/dashboard")}>
            Back to Dashboard
          </Button>
        }
      />
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
        <div>
          <button
            onClick={() => navigate(-1)}
            className="mb-2 flex items-center gap-1.5 text-xs font-medium text-ink-500 hover:text-brand-600"
          >
            <ArrowLeft size={13} /> Back
          </button>
          <div className="flex items-center gap-1.5 text-xs text-ink-400">
            <Link to="/dashboard" className="hover:text-brand-600">
              Dashboard
            </Link>
            <ChevronRight size={12} />
            <span>Scorecard</span>
            <ChevronRight size={12} />
            <span className="font-semibold text-ink-700">{project.projectId}</span>
          </div>
          <h1 className="mt-1 font-display text-2xl font-bold text-ink-900">Project Scorecard</h1>
        </div>
        <Button variant="outline" icon={Download} onClick={() => window.print()} className="no-print">
          Download Scorecard
        </Button>
      </div>

      <div className="flex items-start gap-3 rounded-xl2 border border-brand-200 bg-brand-50 px-4 py-3.5">
        <Info size={18} className="mt-0.5 shrink-0 text-brand-600" />
        <p className="text-sm text-brand-800">
          This score is generated by an AI risk-assessment model to support human review. It is{" "}
          <span className="font-semibold">not proof of fraud or wrongdoing</span> — findings must be verified by the
          concerned District Authority / Ministry official before any action is taken.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-5 lg:grid-cols-3">
        <div className="rounded-xl2 border border-ink-200 bg-white p-6 shadow-card">
          <h3 className="mb-4 font-display text-base font-bold text-ink-900">Project Information</h3>
          <dl className="space-y-3 text-sm">
            {[
              ["Project ID", project.projectId],
              ["Project Name", project.description],
              ["Sector", project.sector],
              ["State", project.state],
              ["District", `${project.district} (${project.districtCode})`],
              ["Assigned IA", project.assignedIA],
              ["Amount Allocated", formatFullINR(project.amountAllocated)],
              ["Start Date", formatDate(project.startDate)],
              ["End Date", formatDate(project.endDate)],
            ].map(([label, value]) => (
              <div key={label} className="flex items-center justify-between gap-4 border-b border-ink-50 pb-2.5">
                <dt className="text-ink-500">{label}</dt>
                <dd className="text-right font-medium text-ink-900">{value}</dd>
              </div>
            ))}
            <div className="flex items-center justify-between gap-4 pt-1">
              <dt className="text-ink-500">Status</dt>
              <dd>
                <StatusBadge status={project.status} />
              </dd>
            </div>
          </dl>
        </div>

        <div className="flex flex-col items-center justify-center rounded-xl2 border border-ink-200 bg-white p-6 shadow-card">
          <h3 className="mb-2 self-start font-display text-base font-bold text-ink-900">Risk Score</h3>
          <RiskGauge score={project.riskScore} level={project.riskLevel} />
          <p className="mt-2 max-w-xs text-center text-sm text-ink-500">
            This project has a {project.riskLevel.toLowerCase()} risk score based on AI analysis of financial,
            timeline, and documentation signals.
          </p>
          <div className="mt-4 grid w-full grid-cols-2 gap-3 text-center text-xs">
            <div className="rounded-lg bg-canvas px-2 py-2.5">
              <p className="font-display text-base font-bold text-ink-900">{project.progressPercent}%</p>
              <p className="text-ink-500">Physical Progress</p>
            </div>
            <div className="rounded-lg bg-canvas px-2 py-2.5">
              <p className="font-display text-base font-bold text-ink-900">{project.expenditurePercent}%</p>
              <p className="text-ink-500">Fund Utilized</p>
            </div>
          </div>
        </div>

        <div className="rounded-xl2 border border-ink-200 bg-white p-6 shadow-card">
          <h3 className="mb-4 font-display text-base font-bold text-ink-900">Score Breakdown</h3>
          <div className="space-y-4">
            {Object.entries(project.breakdown).map(([key, value]) => (
              <div key={key}>
                <div className="mb-1.5 flex items-center justify-between text-sm">
                  <span className="text-ink-700">{BREAKDOWN_LABELS[key]}</span>
                  <span
                    className={classNames(
                      "font-semibold",
                      value >= 65 ? "text-risk-high" : value >= 35 ? "text-risk-medium" : "text-risk-low"
                    )}
                  >
                    {value}%
                  </span>
                </div>
                <div className="h-2 w-full overflow-hidden rounded-full bg-ink-100">
                  <div
                    className={classNames(
                      "h-full rounded-full transition-all duration-700",
                      value >= 65 ? "bg-risk-high" : value >= 35 ? "bg-risk-medium" : "bg-risk-low"
                    )}
                    style={{ width: `${value}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="overflow-hidden rounded-xl2 border border-ink-200 bg-white shadow-card">
        <div className="border-b border-ink-100 px-6 py-4">
          <h3 className="font-display text-base font-bold text-ink-900">Detected Anomalies</h3>
          <p className="mt-0.5 text-xs text-ink-500">Flagged automatically — each item requires manual verification.</p>
        </div>
        {project.anomalies.length === 0 ? (
          <EmptyState icon={ShieldAlert} title="No anomalies detected" description="This project currently shows no AI-flagged irregularities." />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-left text-sm">
              <thead>
                <tr className="border-b border-ink-100 bg-canvas/50 text-xs uppercase tracking-wide text-ink-500">
                  <th className="px-6 py-3 font-semibold">Anomaly ID</th>
                  <th className="px-6 py-3 font-semibold">Anomaly Description</th>
                  <th className="px-6 py-3 font-semibold">Risk Percentage</th>
                  <th className="px-6 py-3 font-semibold">Detected On</th>
                  <th className="px-6 py-3 font-semibold">Status</th>
                </tr>
              </thead>
              <tbody>
                {project.anomalies.map((a) => (
                  <tr key={a.anomalyId} className="border-b border-ink-50">
                    <td className="whitespace-nowrap px-6 py-3.5 font-semibold text-navy-700">{a.anomalyId}</td>
                    <td className="px-6 py-3.5 text-ink-700">{a.description}</td>
                    <td className="px-6 py-3.5 text-ink-700">{a.riskPercentage}%</td>
                    <td className="whitespace-nowrap px-6 py-3.5 text-ink-700">{formatDate(a.detectedOn)}</td>
                    <td className="px-6 py-3.5">
                      <StatusBadge status={a.status} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
